### ISSUE TITLE
Video quality on Safari

### ISSUE THREAD

**Issue by pkl** [Vanilagy/mp4-muxer#15]
H!

I have a hard time getting good quality MP4 videos created on desktop Safari.

This config gives me perfect results in Chrome (frames are encoded from canvas):

```
videoEncoder.configure({
 codec: "avc1.640028",
 width: 720,
 height: 720,
 bitrate: 10_000_000,
 framerate: 30,
 latencyMode: "quality",
});
```

But no matter how I tweak the config Safari creates MP4 videos with ~110 kb/s.

Can anyone share a config that works in Safari?

**Comment by TheForsakenSpirit** [comment]
@pkl iOS safari or macOS safari?
I saw this bug on webkit bug tracker. Seems related https://bugs.webkit.org/show_bug.cgi?id=258060
Also I have revers issue on iOS, files too big independent of configuration.

**Comment by Vanilagy** [comment]
Sadly, not too much I can do here. I'll close this issue as it's not directly related to something in `mp4-muxer`. Feel free to still drop updates if you found a fix for the video quality in Safari.
