### ISSUE TITLE
Error: TS2322: Type '{ codec: string; width: number; height: number; }' is not assignable to type 'undefined'.

### ISSUE THREAD

**Issue by AmitMY** [Vanilagy/mp4-muxer#19]
>    The expected type comes from property 'video' which is declared here on type 'MuxerOptions<ArrayBufferTarget, undefined, undefined>'

Because now the default is `undefined` with no way of changing it:
https://github.com/Vanilagy/mp4-muxer/blob/main/src/muxer.ts#L33-L36

**Comment by Vanilagy** [comment]
Can you show me your code that errors?

**Comment by AmitMY** [comment]
This is only an error in 3.0.0

```ts
      const {Muxer, ArrayBufferTarget} = await import('mp4-muxer');
      this.videoType = 'mp4';
      this.muxer = new Muxer({
        target: new ArrayBufferTarget(),
        video: {
          codec: 'avc',
          width: image.width,
          height: image.height,
        },
      });
  ```

**Comment by Vanilagy** [comment]
Ah yes, I incorrectly used generics in the declaration file. I released a fix in v3.0.1, can you please verify?

**Comment by AmitMY** [comment]
Given your fix, it doesn't work as is.

It seems like I need to modify my definition to:
```ts
new Muxer<ArrayBufferTarget, VideoOptions>({
```

But I can't import it

<img width="567" alt="image" src="https://github.com/Vanilagy/mp4-muxer/assets/5757359/f6403761-241a-42eb-b811-f5aca9565bcf">

**Comment by Vanilagy** [comment]
No you shouldn't have to update your definition, the generics are inferred from what you pass to the Muxer. What is the error now? From the above example, it seems like you're not passing `fastStart`.

**Comment by Vanilagy** [comment]
This works for me in v3.0.1. Note how the second generic is properly inferred from what gets passed:

![CleanShot 2023-10-30 at 12 46 36](https://github.com/Vanilagy/mp4-muxer/assets/1696106/cb618004-c17b-43c8-b17f-2a082ec82faa)

**Comment by AmitMY** [comment]
with `fastStart`, there's no need for explicit typing. thanks!
