### ISSUE TITLE
need some advice on doing live streaming with mp4-muxer

### ISSUE THREAD

**Issue by RavikumarTulugu** [Vanilagy/mp4-muxer#23]
Hi , 
Thanks for a wonderful library, i have used the mp4-muxer library for recording and it worked like a charm. Now, i am looking to do live streaming over dash , any pointers or advice would speed up my efforts. 
Thanks

**Comment by RavikumarTulugu** [comment]
Also it would be good to have fragmentation support for mp4.

**Comment by Vanilagy** [comment]
This library doesn't yet support live-streaming or fMP4 and I currently don't know a lot about this topic, so I'm not sure I can give you any meaningful advice. But my bet would be that you can't easily use this library in its current state to achieve anything live-streamy - I'd need to add fMP4 support then! Maybe I should get to it someday?

**Comment by RavikumarTulugu** [comment]
okay, thanks for the reply. I am looking at webm-muxer for live streaming. hopefully it will solve my need.

**Comment by Vanilagy** [comment]
Awesome, let me know if it worked :)
