### ISSUE TITLE
Error when using FileSystemWritableFileStreamTarget

### ISSUE THREAD

**Issue by Mat-thieu** [Vanilagy/mp4-muxer#24]
The following error:

![Screenshot 2023-11-30 at 15 26 27](https://github.com/Vanilagy/mp4-muxer/assets/7059091/5c6be8a6-28da-4e94-b4d8-0ba73f8ccb75)

Occurs when trying to use `FileSystemWritableFileStreamTarget` with fileWriter.

This write function (in the build code) is expecting a blob not an object

![Screenshot 2023-11-30 at 15 27 36](https://github.com/Vanilagy/mp4-muxer/assets/7059091/f4f7be3c-7b7f-4bc1-8192-aec710f58fda)

For now I've worked around the issue by wrapping the fileWriter

```js
   const wrapFileWriter = (fileWriter) => {
        const originalWrite = fileWriter.write;
        const modifiedWrite = (payload) => {
            const blob = new Blob([payload.data]);
            originalWrite.call(fileWriter, blob);
        }
        fileWriter.write = modifiedWrite;
        return fileWriter;
    };
    let muxer = new Mp4Muxer.Muxer({
	target: new Mp4Muxer.FileSystemWritableFileStreamTarget(wrapFileWriter(fileWriter)),
        ...
    }
```

**Comment by Vanilagy** [comment]
The `FileSystemWritableFileStreamTarget` expects a [`FileSystemWritableFileStream`](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemWritableFileStream) as a parameter! [Its `write` method](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemWritableFileStream/write) also accepts ArrayBuffers as input.

It seems like you are passing it something else. How are you getting your `fileWriter`?

**Comment by Mat-thieu** [comment]
@Vanilagy 

Aah right, I see! Indeed I'm passing a different object. I'm passing it a `FileWriter` which is returned from a [fileEntry.createWriter](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemFileEntry/createWriter) directly.

I'm obtaining this fileEntry from the following code

```js
export default function requestTempFile(name, sizeInMb) {
    return new Promise((resolve) => {
        const fileSystem = (window.requestFileSystem || window.webkitRequestFileSystem);
        fileSystem(window.TEMPORARY, sizeInMb * 1024 * 1024, (fs) => {
            fs.root.getFile(name, { create: true }, (fileEntry) => {
                resolve(fileEntry);
            });
        });
    });
}
```
Which is a non-standard, chromium-specific way of creating a sandboxed file.

It's a slightly different use case, it can likely just be handled by the StreamTarget directly

**Comment by Vanilagy** [comment]
Yes exactly, these custom cases are supposed to be handled by `StreamTarget`. It'll be very easy and quick to use! In fact, `FileSystemWritableFileStreamTarget` is nothing but a very thin wrapper around `StreamTarget`.

**Comment by Vanilagy** [comment]
Has your issue been resolved?

**Comment by Vanilagy** [comment]
I'll close this issue for now as it seems stale, so I assume your issue has been resolved. If you still need help with something, feel free to reopen it :)
