### ISSUE TITLE
Questions about the size of video composites

### ISSUE THREAD

**Issue by mtsee** [Vanilagy/mp4-muxer#26]
The video synthesized using canvas screenshots is particularly large. The 10-minute video (1280 * 720 30fps) is about 2G. What ideas can you use to reduce the size of the video?

**Comment by Vanilagy** [comment]
The way to reduce the size of media files usually involves reducing the bitrate, when you can't reduce the resolution or framerate further. Long videos often get into the multi-gigabyte range, but that shouldn't be the case for a 10-minute video, unless your bitrate is crazy high (which is okay, if you want little loss).

**Comment by Vanilagy** [comment]
I'll close this issue for now as it seems stale. If you still need help with something, feel free to reopen it :)
