### ISSUE TITLE
strange codec mismatch

### ISSUE THREAD

**Issue by ldenoue** [Vanilagy/mp4-muxer#3]
Hello!

I'm using this muxer to generate MP4 videos using VideoEncoder to which I pass either `avc1.F4E034` or `avc1.42001F` codecs.

However, when I try to demux the generated videos using mp4box.js it returns different codec names.

I.e. the mp4 generated using `avc1.F4E034` is shown by mp4box as having the codec `avc1.42002a` and the one generated using `avc1.42001F` is now `avc1.42031e`. That second one `avc1.42031e` makes the VideoDecoder fail.

Is there a reason why?

**Comment by Vanilagy** [comment]
Hi! This is strange, but I'm afraid there is not much I can do about this! The codec string is never literally passed into the muxer, but the decoder configuration generated by the encoder is. This is series of bytes generated by the browser that are to be saved in the file; I do this. If the decoder then thinks it's a different codec from the encoder, there's a chance these bytes aren't being generated properly by Chrome. In fact, I recently found a bug with this which I also reported, here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1433391

So yeah, not much I can about this. Can you try sticking to codecs that don't error when decoding?

**Comment by ldenoue** [comment]
It now works when the video width and height are `640x640`. It failed when the video size was `320x320`.
Is there a reason you're aware of?
Free free to close this, but I'm still curious.

**Comment by Vanilagy** [comment]
No idea! Let's hope the wizards at Chromium know more!

**Comment by Vanilagy** [comment]
> This probably not related. There is not enough information in the bug report to diagnose it (actual error messages, bitstreams, and code would be necessary), but it is not surprising for VideoEncoder to produce a stream with a different profile than requested. The only requirement is that the profile is decodable by a decoder that supports the requested profile. FWIW, "avc1.F4E034" is not a real profile string, there is no AVC level 244.

**Comment by ldenoue** [comment]
Thanks @Vanilagy I was now able to make the muxer work by using the `avc1.640034` video codec. The demuxer I use (mp4box) is still reporting a different codec, but at least the ones reported are working with VideoDecoder.
