### ISSUE TITLE
Error:  Cannot call 'flush' on a closed codec. In Demo

### ISSUE THREAD

**Issue by Pensarfeo** [Vanilagy/mp4-muxer#32]
Hi, I was trying to run the demo and I go the following error:

DOMException: Failed to execute 'flush' on 'AudioEncoder': Cannot call 'flush' on a closed codec.
    at HTMLButtonElement.endRecording (https://vanilagy.github.io/mp4-muxer/demo/script.js:140:22)

I am using chrome latest version on linux.

**Comment by Vanilagy** [comment]
Is there any error before that? Seems like an issue related to the AudioEncoder.

**Comment by Pensarfeo** [comment]
Yes, 

![image](https://github.com/Vanilagy/mp4-muxer/assets/14980193/fad972d5-2cdd-4a65-800a-acbfbc742f2e)

**Comment by Vanilagy** [comment]
Yes, seems like your browser doesn't support encoidng AAC on your system. Can't really say why not! You can try playing around with other codec strings and codecs until you find one that works. These are the ones for AAC:

https://www.w3.org/TR/webcodecs-aac-codec-registration/#fully-qualified-codec-strings

**Comment by Pensarfeo** [comment]
Thanks!
