### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by bil-ash** [Vanilagy/mp4-muxer#33]
Chrome for android version 120 added support for aac in webcodecs but I get error while using mp4-muxer(on 2 different android devices running 2 different OS version but chrome 120). Things are fine on desktop. The error screenshot is provided below. 
![mp4muxer error](https://github.com/Vanilagy/mp4-muxer/assets/33216854/033990a4-a213-4917-a96e-bca8b99f5bc9)

Seems similar to #32 . 
Also, support for hls straming (fMP4) would be great feature addition.

**Comment by Vanilagy** [comment]
Even though this error occurs in my demo, it seems like it is a problem with AudioEncoder and not my library. I suggest you play around with creating several AudioEncoders and passing it AudioData and seeing what works. Maybe there's a bitrate mismatch going on?

**Comment by Vanilagy** [comment]
I'll close this issue for now as it seems stale. If you still need help with something, feel free to reopen it :)
