### ISSUE TITLE
Is there an issue with the data generated by StreamTarget?

### ISSUE THREAD

**Issue by samdrivertlol** [Vanilagy/mp4-muxer#4]
Is there an issue with the data generated by StreamTarget?

I am using Node.js API (electron app) to write data to the file system.

One approach is to use StreamTarget to continuously write data to the file.
Another approach is to use ArrayBufferTarget and then write the data to the file at the end.

The file written with StreamTarget appears to be corrupted.
The file written with ArrayBufferTarget is fine.

Here is an example code.
```
  const writeStream1 = fs.createWriteStream("file-1.mp4");
  const writeStream2 = fs.createWriteStream("file-2.mp4");
    
  // videoMuxer1 use fileTarget1
  const fileTarget1 = new Mp4Muxer.StreamTarget(
    (data, position) => {
      WriteStream.write(data);
    },
    () => {
      WriteStream.end();
      // file-1.mp4 is fail
    }
  );
  
  // videoMuxer2 use fileTarget2
  const fileTarget2 = new Mp4Muxer.ArrayBufferTarget();
  const onStop = () => {
    let { buffer } = videoMuxer2.target;
    writeStream2.write(Buffer.from(buffer));
    writeStream2.end(); // in electron node
    // file-2.mp4 is success
  };
  
  const videoMuxer1 = new Mp4Muxer.Muxer(...);
  const videoMuxer2 = new Mp4Muxer.Muxer(...);
  videoMuxer1.addVideoChunk(chunk, meta);
  videoMuxer2.addVideoChunk(chunk, meta);
  videoMuxer2.addAudioChunk(chunk, meta);
  videoMuxer2.addAudioChunk(chunk, meta);
```

**Comment by Vanilagy** [comment]
When writing data fired by the StreamTarget, you need to make sure to write the passed data at the correct position. In your code, you're currently ignoring the position argument in your handler.

Data fired by the StreamTarget is not necessarily sequential, and therefore you need to respect this position argument. Not sure if non-sequential writes are possible with a Node.js Writable; if not, you may need to use fs.write instead.
