### ISSUE TITLE
Could you please kindly add support to the demo with mp3 audio?

### ISSUE THREAD

**Issue by xeoshow** [Vanilagy/mp4-muxer#40]
Hello,

For the below demo, could you please kindly add support to the demo with mp3 audio option? Just have no idea how to use our own mp3 file. Thanks a lot.

```
https://vanilagy.github.io/mp4-muxer/demo/
```

**Comment by Vanilagy** [comment]
Not sure that works as described in #29, AudioEncoder can't encode MP3 yet. If you want to combine an existing MP3 file into a video, you *could* technically parse the file yourself and extract the various segments, but that requires time to read into the MP3 specification.

I don't wanna be too "StackOverflowy" here, but I recommend you not use MP3, the format has long been superceded. Instead, decode the MP3 file you have and reencode it using a better codec such as AAC or Opus. See #16 for how to do that.

**Comment by Vanilagy** [comment]
Closed for inactivity.

**Comment by weepy** [comment]
Shame it doesn’t work with mp3. There’s. Very few truly cross platform audio formats (iOS ruining the party ).

**Comment by Vanilagy** [comment]
What's wrong with AAC? Apple was literally an early adopter of this format. Quote Wikipedia:

> AAC is the default or standard audio format for [iPhone](https://en.wikipedia.org/wiki/IPhone), [iPod](https://en.wikipedia.org/wiki/IPod), [iPad](https://en.wikipedia.org/wiki/IPad), [Nintendo DSi](https://en.wikipedia.org/wiki/Nintendo_DSi), [Nintendo 3DS](https://en.wikipedia.org/wiki/Nintendo_3DS), [Apple Music](https://en.wikipedia.org/wiki/Music_(software)),[[a]](https://en.wikipedia.org/wiki/Advanced_Audio_Coding#cite_note-8) [iTunes](https://en.wikipedia.org/wiki/ITunes), [DivX Plus Web Player](https://en.wikipedia.org/wiki/DivX#DivX_Plus_Web_Player), [PlayStation 4](https://en.wikipedia.org/wiki/PlayStation_4) and various [Nokia](https://en.wikipedia.org/wiki/Nokia) [Series 40](https://en.wikipedia.org/wiki/Series_40) phones. It is supported on a wide range of devices and software such as [PlayStation Vita](https://en.wikipedia.org/wiki/PlayStation_Vita), [Wii](https://en.wikipedia.org/wiki/Wii), digital audio players like [Sony Walkman](https://en.wikipedia.org/wiki/Sony_Walkman) or [SanDisk Clip](https://en.wikipedia.org/wiki/SanDisk_Clip), [Android](https://en.wikipedia.org/wiki/Android_(operating_system)) and [BlackBerry](https://en.wikipedia.org/wiki/BlackBerry) devices, various in-dash car audio systems,[[when?](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Dates_and_numbers#Chronological_items)][[vague](https://en.wikipedia.org/wiki/Wikipedia:Vagueness)] and is also one of the audio formats used on the [Spotify](https://en.wikipedia.org/wiki/Spotify) web player.

**Comment by weepy** [comment]
Is it possible to encode to AAC in the browser from an AudioBuffer?

**Comment by Vanilagy** [comment]
@weepy Yes definitely! My demo for this very library includes an AAC encoder! I think thus far, iOS/Safari only supports `VideoEncoder`, so no audio. I agree, totally lame. I guess using a WASM AAC encoder would be helpful for that case as a fallback.
