### ISSUE TITLE
Export MuxerOptions

### ISSUE THREAD

**Issue by joghyrt** [Vanilagy/mp4-muxer#42]
Hello!

Could you export MuxerOptions? 

now:

`export { Muxer, ArrayBufferTarget, StreamTarget, FileSystemWritableFileStreamTarget };`

then:

`export { Muxer, ArrayBufferTarget, StreamTarget, FileSystemWritableFileStreamTarget, MuxerOptions };`

It would reduce code lines significantly in my project.

Thank you!

**Comment by Vanilagy** [comment]
Good point. In the meantime, you should be able to do
```ts
type Constructor = new (...args: any[]) => any;

type FirstConstructorParameter<T extends Constructor> = 
    ConstructorParameters<T> extends [infer P, ...any[]] ? P : never;

type MuxerOptions = FirstConstructorParameter<typeof Muxer>;
```

**Comment by Vanilagy** [comment]
v4.1.0 now exports the `MuxerOptions` type.

**Comment by joghyrt** [comment]
@Vanilagy thank you so much! It was super fast!
