### ISSUE TITLE
video from still image and an mp3

### ISSUE THREAD

**Issue by weepy** [Vanilagy/mp4-muxer#43]
Hey - this is an amazing project! Is it possible to create an mp3 from a still image and an mp3 ?

**Comment by Vanilagy** [comment]
@weepy Hi, and thank you so much! Should be possible! For the video, you can create a VideoFrame with timestamp 0 and the duration equal to the length of your audio. And the audio you'd need to decode and then reencode. As you know by now, encoding MP3 isn't really possible at the moment, and iOS doesn't like encoding audio in general, but besides that, it should work.

Do you need help with anything specific, or are you already further in this pursuit anyway?
