### ISSUE TITLE
Does mp4-muxer support muxer encoding data for multiple audioEncoders simultaneously

### ISSUE THREAD

**Issue by qingwufong** [Vanilagy/mp4-muxer#50]
Hello Vanilagy, mp4-muxer is a great library. May I ask if it supports muxer encoding data for multiple audioEncoders simultaneously？I know that muxers support both a video stream and an audio stream simultaneously，but Is it feasible for me to combine multiple audio streams played simultaneously with encoded video stream for export.

**Comment by qingwufong** [comment]
pls mark this issue as question or help. thx

**Comment by qingwufong** [comment]
Vanilagy，Thanks for your guidance，Your reply is fast [thumb up]. I will give it a try and hope it works   ；-）

**Comment by Vanilagy** [comment]
You're welcome! Let me know if there's any updates.

**Comment by qingwufong** [comment]
> You're welcome! Let me know if there's any updates.
I have tested the code you sent above and it is feasible，that`s great. Perhaps copying audioData to temporary buffer like this: `audioData.copyTo(tempBuffer, { planeIndex: 0 })`.

It must Ensure all AudioData objects have the same number of frames, sampleRate, and format，but most of the time these attributes of audio are different. May I ask why the sampleRate and number of frames of combined audio must be the same? Is there a way to combine audio data with different attributes? thanks~

**Comment by qingwufong** [comment]
> You're welcome! Let me know if there's any updates.
I have tested the code you sent above and it is feasible，that`s great. Perhaps copying audioData to temporary buffer like this: `audioData.copyTo(tempBuffer, { planeIndex: 0 })`.

It must Ensure all AudioData objects have the same number of frames, sampleRate, and format，but most of the time these attributes of audio are different. May I ask why the sampleRate and number of frames of combined audio must be the same? Is there a way to combine audio data with different attributes? thanks~

**Comment by Vanilagy** [comment]
Can you specify how the attributes of audio are different for you? What are your audio sources, and what does an AudioData instance look like for you?

Of course there are always to combine audio data with different sample rates & frame count, but it gets more complicated. For different samples rates you need to perform resampling, for example. If the channel count also doesn't match, this becomes even more complicated. Then you get into the realm of general audio mixing, which is much better served by just using the `Web Audio API`. But again, I don't know what your audio sources are.

Since this issue is not directly related to `mp4-muxer`, I'll close this issue. Still happy to give you pointers though!

**Comment by qingwufong** [comment]
> Can you specify how the attributes of audio are different for you? What are your audio sources, and what does an AudioData instance look like for you?

My audio sources is more than one MP3 files. For example, audioDataArray looks like below:
![image](https://github.com/Vanilagy/mp4-muxer/assets/6860888/d4049946-c6c3-4d07-b48e-970a303d3aa7)

**Comment by qingwufong** [comment]
Okay, next I will try to align the sampleRate and frame count of the audioData to be combined by resampling.

**Comment by Vanilagy** [comment]
@qingwufong Where do the MP3 files come from? If you have the option to use them with the Web Audio API, then I'd simply mix them together there. It takes care of everything; resampling and even channel mismatch (up/down mixing). I'd then pipe them into a `ScriptProcessorNode` (it's deprecated, but I think it's still viable) and then use the data this node receives to construct `AudioData` objects yourself.

You really shouldn't be needing to implement an audio mixing pipeline yourself, the web already has tools for this.

**Comment by qingwufong** [comment]
@Vanilagy 

> Where do the MP3 audio sources come from?

mp3 file is downloaded by http request, and audioData from HTML5 audio player:
``` javascript
      const audioTrack = mediaEle.captureStream().getAudioTracks()[0]
      let trackProcessor = new MediaStreamTrackProcessor({
        track: audioTrack
      })
 
      const consumer = new WritableStream({
        write: (audioData) => {
          // store audioData here...
        }
      })
      trackProcessor.readable.pipeTo(consumer)
```
Yes, I have the option to use them with the Web Audio API, But currently, I am not sure how to resample using the Web Audio API. Could you provide some more guidance ；-)

**Comment by Vanilagy** [comment]
You're using the wrong approach! There's no need to go anywhere near media streams when your input is an mp3 file; you can do it entirely in the Web Audio API. If you don't have any real-time data (data that you don't know when the video rendering begins), I suggest using the offline context. Here (untested):

```ts
// Fetch the first MP3 file
const response1 = await fetch('https://example.com/audio1.mp3');
const arrayBuffer1 = await response1.arrayBuffer();

// Fetch the second MP3 file
const response2 = await fetch('https://example.com/audio2.mp3');
const arrayBuffer2 = await response2.arrayBuffer();

// Create an AudioContext for decoding
const audioContext = new AudioContext();

// Decode the audio data
const audioBuffer1 = await audioContext.decodeAudioData(arrayBuffer1);
const audioBuffer2 = await audioContext.decodeAudioData(arrayBuffer2);

// Define the duration for the mix
const duration = 10; // seconds
const sampleRate = 44100; // Hz
const numberOfChannels = 2; // stereo

// Create an OfflineAudioContext for mixing
const offlineAudioContext = new OfflineAudioContext(numberOfChannels, sampleRate * duration, sampleRate);

// Create buffer sources
const source1 = offlineAudioContext.createBufferSource();
const source2 = offlineAudioContext.createBufferSource();

source1.buffer = audioBuffer1;
source2.buffer = audioBuffer2;

source1.connect(offlineAudioContext.destination);
source2.connect(offlineAudioContext.destination);

// Start the sources at the same time
source1.start(0);
source2.start(0);

// Render the mixed audio
const renderedBuffer = await offlineAudioContext.startRendering();

// Prepare data for AudioData
const numberOfFrames = renderedBuffer.length;
const audioDataInit = {
    format: "f32-planar" as const,
    sampleRate: sampleRate,
    numberOfFrames: numberOfFrames,
    numberOfChannels: numberOfChannels,
    timestamp: 0,
    data: new Float32Array(numberOfFrames * numberOfChannels)
};

// Interleave the channel data
for (let channel = 0; channel < numberOfChannels; channel++) {
    const channelData = renderedBuffer.getChannelData(channel);
    for (let i = 0; i < numberOfFrames; i++) {
        audioDataInit.data[channel * numberOfFrames + i] = channelData[i];
    }
}

// Create the AudioData object
const audioData = new AudioData(audioDataInit);

console.log(audioData);
```

These are some pointers. If you need more help, I suggest you do web searches on these topics or ask ChatGPT, there's a lot of reference out there! As much as I like to help, I don't have infinite time :(

**Comment by qingwufong** [comment]
Because I am currently in a playback scenario, I obtained audioData from the player stream. Yes, I may have used the wrong approach.
Thank you for your time. Not only did it help me, but it also deeply touched me. I will buy you a cup of coffee as a token of gratitude. Thank you again for your help!! @Vanilagy
