### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by erwanvivien** [Vanilagy/mp4-muxer#52]
Hey, huge fan of this library! 💜 

I've recently change from using minimp4 to use this muxer! It works like a charm for most players but I seem to have lost some compatibility:

# Repros

<details>

<summary>For colorful repros</summary>

[download new](https://github.com/Vanilagy/mp4-muxer/assets/44021072/9189fe09-07ac-4dc5-bc2a-d52fa5c8c9b0).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/9189fe09-07ac-4dc5-bc2a-d52fa5c8c9b0

[download old](https://github.com/Vanilagy/mp4-muxer/assets/44021072/bf85be52-98a1-4fcd-b2a4-841e7de67912).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/bf85be52-98a1-4fcd-b2a4-841e7de67912

</details>

<details>

<summary>For minimal repros</summary>

[download new](https://github.com/Vanilagy/mp4-muxer/assets/44021072/936bfd70-e43f-4244-824f-bd6d019531af).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/936bfd70-e43f-4244-824f-bd6d019531af

[download old](https://github.com/Vanilagy/mp4-muxer/assets/44021072/5a6e7044-6e69-483b-87d6-f5e947f52457).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/5a6e7044-6e69-483b-87d6-f5e947f52457

</details>

# Errors

Here is a screenshot of an error message from PPT:

![image](https://github.com/Vanilagy/mp4-muxer/assets/44021072/8b3f3729-7ee8-4177-86a8-0354b99f2b1f)

This seems to have been fixed by installing `K-Lite_Codec_Pack_1835_Standard`

Here is the diplayed embedded version in Slack 

<img width="508" alt="Screenshot 2024-06-12 at 11 05 49" src="https://github.com/Vanilagy/mp4-muxer/assets/44021072/f92666c7-28a5-4cde-8bbe-0ee7a255d12f">

# Small investigation

From the [MP4Box filereader](https://gpac.github.io/mp4box.js/test/filereader.html) page I could found small differences in the exported videos (I used the minimal ones)

### New one

<img width="1512" alt="Screenshot 2024-06-12 at 11 12 07" src="https://github.com/Vanilagy/mp4-muxer/assets/44021072/d4afb231-a530-42cf-be6c-02032ffa4f3c">

### Old one

<img width="1514" alt="Screenshot 2024-06-12 at 11 12 46" src="https://github.com/Vanilagy/mp4-muxer/assets/44021072/db2e9bdb-1cb9-42a4-a598-505ab93d2dfc">

- Could it be the [brands](https://cconcolato.github.io/mp4ra/filetype.html#)? 
- Could it be the 0 duration in the header?
- Could it be the 64 bit thing that powerpoint reports? I saw some mentions of 64-bit in the codebase: [[1]](https://github.com/Vanilagy/mp4-muxer/blob/bba6ec99deb52111b745095559a7e376576d18fc/src/box.ts#L597) [[2]](https://github.com/Vanilagy/mp4-muxer/blob/bba6ec99deb52111b745095559a7e376576d18fc/src/muxer.ts#L231)

# Thanks for your time & insights

I'm happy to help fix the bug if you can provide guidance 👍

**Comment by erwanvivien** [comment]
Updated: This is not urgent at all and seems to be related to `fastStart: "fragmented"`

When I change to `false` / `"in-memory"` it seems to be playing well in Slack at least!

<details>

<summary>Minimal repros (false / in-memory)</summary>

[donwload `fastStart: false`](https://github.com/Vanilagy/mp4-muxer/assets/44021072/638fcb9b-3a08-4861-b8fa-72ad07858661).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/638fcb9b-3a08-4861-b8fa-72ad07858661


[donwload `fastStart: "in-memory"`](https://github.com/Vanilagy/mp4-muxer/assets/44021072/3d8b3586-e309-40b4-83f5-9bce55075d87).

https://github.com/Vanilagy/mp4-muxer/assets/44021072/3d8b3586-e309-40b4-83f5-9bce55075d87

</details>

<details>

<summary>MP4Box filereader analysis</summary>

### `fastStart: false`

<img width="1511" alt="Screenshot 2024-06-12 at 11 44 58" src="https://github.com/Vanilagy/mp4-muxer/assets/44021072/e4e0206c-e93d-4b8f-9a87-ef1e6e712e91">

### `fastStart: "in-memory"`

<img width="1511" alt="Screenshot 2024-06-12 at 11 44 46" src="https://github.com/Vanilagy/mp4-muxer/assets/44021072/023bfe0b-d0c1-45fb-90cd-b9b851a18f9e">

</details>

**Comment by Vanilagy** [comment]
It could be that PowerPoint doesn't like fragmented MP4, perhaps? We should verify that it's that and not this library having an error in its fMP4 file structure. Try piping your MP4 file (the one that isn't fragmented) through this:
```
ffmpeg -i input.mp4 -c copy -f mp4 -movflags +frag_keyframe+empty_moov+default_base_moof output.fmp4
```
This makes it fragmented. See if you can pop that into PowerPoint.

**Comment by erwanvivien** [comment]
Thanks for the FFmpeg command!

Indeed this one does not displays on Slack for example. So that's great, no bugs really in the code 🎉 

My only question for my knowledge then is why in the fragmented version, the headers seems broken? I know fragmented splits the header in chuncks, is it MP4Box that does not read them or it's expected to show duration 0 / or filesize NaN?

Thanks for the prompt replies 🙏

**Comment by Vanilagy** [comment]
The header is not broken, it's just that not all metadata is contained in the header anymore. In the header in a fragmented file, a lot of the data is left blank (like duration, sample data), and it's completed using the `moof` boxes spread throughout the file. That's why it's called fragmented!

**Comment by erwanvivien** [comment]
Yep that was my understand with bad wording haha, thanks for the clarifications on the blank spaces 🙏 
Much appreciated
