### ISSUE TITLE
Whether mp4-muxer.js supports muxer as mp4-front instead of a mp4-back?

### ISSUE THREAD

**Issue by yangfangfang1204** [Vanilagy/mp4-muxer#54]
i addAudioChunk and addVideoChunk to the mp4-muxer，muxer.finalize(); and download muxer.target.buffer; i find the buffer is back mp4(mdat) , not front-mp4(moov) , so it supports mp4-front？

**Comment by Vanilagy** [comment]
Read the `fastStart` section in the README.
