### ISSUE TITLE
output file can't be played everywhere. something missing

### ISSUE THREAD

**Issue by 0-mandrixx-0** [Vanilagy/mp4-muxer#6]
Hi,

I managed to get the muxing working but the output file seems to be corrupted in some way. it can be played with VLC and chrome on my computer. but it fails playing on my android phone or with windows media player, preview is not shown in windows folder and it can't be opened by https://gpac.github.io/mp4box.js/test/filereader.html

if I just remux with ffmpeg with copy, it works fine. ffmpeg adds something when I compare the ffprobes :
[mov,mp4,m4a,3gp,3g2,mj2 @ 000000000284af40] Processing st: 0, edit list 0 - media time: 0, duration: 127492
[mov,mp4,m4a,3gp,3g2,mj2 @ 000000000284af40] Unknown dref type 0x206c7275 size 12
[mov,mp4,m4a,3gp,3g2,mj2 @ 000000000284af40] Processing st: 1, edit list 0 - media time: 0, duration: 483336

also mediainfo shows some extra lines for the remuxed ffmpeg version :
- for global:
Overall bit rate mode                    : Variable
encoded-date and tagged-date
- video :
stream-size , encoded-date and tagged-date
- audio :
Bit rate mode                            : Variable
stream-size , encoded-date and tagged-date

I use avc1.420033 and mp4a.40.2

my 2 test files :
https://keny.toys/tmp/test_mp4muxer.mp4
https://keny.toys/tmp/test_remuxedffmpeg.mp4

**Comment by 0-mandrixx-0** [comment]
did some more tests. fails on iOS (iphone, ipad and mac) with safari, quicktime and native read. works only with a desktop chrome and VLC

**Comment by Vanilagy** [comment]
Alright, very interesting, I was able to reproduce the error. So, when I run the demo of this library, the resulting file actually runs perfectly in QuickTime and everything - but seems like I'm still doing something wrong, but only sometimes. Could you perhaps share how you're creating this file exactly? I remember when coding this library initially, files with highly varying frame rate refused to play in some players. But clearly, FFmpeg seems to be fixing _something_ here, so I can try to inspect what it's doing differently.

So yeah, could you share a bit of the code that's generating this video, and also confirm that the demo is indeed working for you?

**Comment by 0-mandrixx-0** [comment]
hi,

made a bunch of tests with the demo, changing all the parameters, and I think I've found the issue. it's linked to the avc: { format: 'annexb' } in the videoEncoder config. which was mandatory in chrome 113. I don't know exactly what is it for. it works without this option and it seems chrome 114 don't require it.

I will make some more extensive tests monday. I use your library in a complex thing that produces a great variety of resolutions, framerate, length, codecs. Will let you know about the results

thanks a lot

**Comment by Vanilagy** [comment]
Was annexb required? I never set it and it worked fine for me - that's also what's done in the demo. But yes, keep me updated and we'll figure this out!

**Comment by 0-mandrixx-0** [comment]
I've realized that without annex-b, I can open the file everywhere but I can't hear the sound if I'm not opening with chrome or VLC.
everything seems to be there and remuxing with ffmpeg fixes the problem. the demo with the microphone input is working fine so I'm trying to find out what's different

**Comment by Vanilagy** [comment]
Thanks for doing some more research! So; is there anything this library should do or change? Or is this not a bug?

**Comment by 0-mandrixx-0** [comment]
not a bug. I hope google will keep webcodec as it is now for h264/aac

**Comment by Vanilagy** [comment]
Awesome. If you think this is an issue with Chromium though, make sure to report it!
