### ISSUE TITLE
about showSaveFilePicker

### ISSUE THREAD

**Issue by mtsee** [Vanilagy/mp4-muxer#64]
I have a request to perform video synthesis in puppeteer, but puppeteer cannot operate the confirmation pop-up window of showSaveFilePicker. Can I return the synthesized data through a callback function and then fetch it to the node environment for video synthesis?

**Comment by Vanilagy** [comment]
I'm no expert in Puppeteer so I can't help you with this one. But if there's a way to pass data from Puppeteer back into Node, you'll be able to use `StreamTarget` without issues.

Closing this issue as it's quite unrelated to this library.
