### ISSUE TITLE
Feature Request: Support for setting video cover

### ISSUE THREAD

**Issue by Tianj0o** [Vanilagy/mp4-muxer#79]
Hi Vanilagy, I have been using mp4-muxer and find it very useful thanks for creating and maintaining this project! In the process of using it, I came across a scene where I needed to set up a video cover.
I have implemented this functionality in my fork. It allows users to specify an image to be used as the cover of a video when creating an MP4 file.
If that sounds like something you'd like to include in your project, I'd be happy to submit a pull request.

**Comment by Vanilagy** [comment]
That's cool, can you show me the fork?

**Comment by Tianj0o** [comment]
https://github.com/Tianj0o/mp4-muxer/commit/c53882421bde432ab743f2b40a0e5087bebc4f8e

**Comment by Vanilagy** [comment]
No longer interested? I was keeping this around for when I get to it.

**Comment by Tianj0o** [comment]
No, I’m still interested in it! I’ve submitted a PR, whenever you’re ready. Let me know if you have any feedback or if any changes are needed.
Thanks for your time and for maintaining this project!
