### ISSUE TITLE
Removed onDone inside StreamTarget

### ISSUE THREAD

**Issue by KaliaJS** [Vanilagy/mp4-muxer#80]
Hello Vanilagy,

You removed onDone with Commit 89d0aef. I was using it with electron.js ([see issue](https://github.com/Vanilagy/webm-muxer/issues/25))

Could you provide some explanation about whether I still need it with the new version of mp4-muxer (and webm-muxer)? If so, how can I implement it in the new version?

```javascript
      target: new StreamTarget(
        (data, position) =>
          (lastPromise = lastPromise.then(() =>
            fileHandle.write(data, 0, data.length, position)
          )),
        () => (lastPromise = lastPromise.then(() => fileHandle.close())),
        { chunked: true }
      ),
```

**Comment by Vanilagy** [comment]
Hey @KaliaJS, simply place your `onDone` logic after the call to `muxer.finalize()`. I realized it was equivalent to this and therefore removed it from the API. In the future, I'll write better release notes / migration notes for this sorta stuff.

**Comment by KaliaJS** [comment]
Okey perfect, Thank you !
